name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Load Google Api Key from secrets
        env:
          UN_SPLASH_API_KEY: ${{ secrets.UN_SPLASH_API_KEY }}
          UN_OFFICIAL_GITHUB_API_KEY: ${{ secrets.UN_OFFICIAL_GITHUB_API_KEY }}
        run: |
          touch local.properties
          echo UN_SPLASH_API_KEY="$UN_SPLASH_API_KEY" >> local.properties
          echo UN_OFFICIAL_GITHUB_API_KEY="$UN_OFFICIAL_GITHUB_API_KEY" >> local.properties
          echo "cat local.properties"
          cat .local.properties
      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build the app
        run: ./gradlew assembleRelease --stacktrace
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: release.apk
          path: ${{steps.sign.outputs.signedReleaseFile}}
      - name: Get App version code
        id: version
        run: |
          echo "::set-output name=commits::$(git rev-list --count HEAD)"
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.commits }}
          release_name: Release v.1.${{ steps.version.outputs.commits }}
        env:
          GITHUB_TOKEN: ${{ secrets.UN_OFFICIAL_GITHUB_API_KEY }}
      - name: Publish package
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.UN_OFFICIAL_GITHUB_API_KEY  }}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.UN_OFFICIAL_GITHUB_API_KEY }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.sign.outputs.signedReleaseFile }}
          asset_name: signed-app.apk
          asset_content_type: application/zip
